### ISSUE TITLE
Virgo donation items may be more than cosmetic.

### ISSUE THREAD

**Issue by cebutris** [Tk420634/ARFS-2#124]
Like people spawn with guns and stuff. It's mostly cosmetics, but some aren't.

I took a quick look and it seems like some people spawn with Central Command attire, too. Not sure how @Tk420634 feels about that.

I'm working on fixing this, though I don't know if I should restrict CentComm stuff as donator items.

**Comment by cebutris** [comment]
I also noticed that some people have melee weapons in their custom items. I think, rather than remove, it would be better to bump force down to 10 at maximum (you can get 10 force items in the regular loadout, anyway)

Again this is up to @Tk420634 or some other design lead if I should just axe it or nerf it

**Comment by Tk420634** [comment]
Yeah, I largely agree with Cebu on this.  That they should be bumped down to force 10 or so.  Firearms are a bit iffy, and could (read: should) be locked to jobs that would normally be capable of getting them.  But I have no idea where to start on something like this. = v=
