### ISSUE TITLE
Missing power wire and air pipes under south locker room door

### ISSUE THREAD

**Issue by Hibou48888** [Tk420634/ARFS-2#152]
#### Brief description of the issue
There's a missing power supply wire and air supply/scrubber pipes under the southern locker door that is cutting power and stopping air circulation to the workout room and pool

#### What you expected to happen
The power network supplies power to all APCs/air is there also 

#### What actually happened
The pool and workout room were without power and also air circulation

#### Steps to reproduce
- Set up engine
- Watch as the pool/workout room don't receive power

#### Code Revision
- master - 2017-08-28
 
#### Anything else you may wish to add:
- It's the southern door of the locker room

**Comment by Tk420634** [comment]
This got fixed a while back, I don't check issues often tho
