### ISSUE TITLE
Shuttle doors and docks.

### ISSUE THREAD

**Issue by gozulio** [Tk420634/ARFS-2#30]
Shuttle doors dont auto close, or force close and bolt before the shuttle leaves.
Shuttle dock doors dont bolt close before the shuttle leaves.
These apply to every "shuttle" it seems.

**Comment by Tk420634** [comment]
WE FIXED THIS RIGHT?

**Comment by Tk420634** [comment]
OKAY YOU SAID YES IN VOICE CHAT
