### ISSUE TITLE
Anomaly lab emitter

### ISSUE THREAD

**Issue by gozulio** [Tk420634/ARFS-2#33]
The anom lab only has one emitter and its facing the wrong direction.
The emitters are their to both either charge or destroy items in the anomaly test chambers. the mini conveyor and airtight flap setup not only make little sense in terms of  safety but the emitter firing into it is pointed at a reinforced wall bordering the hallway.

**Comment by Mewchild** [comment]
Emitter is facing north as intended.
The airtight flap system and conveyor is an old safety mechanism, for gas producers/converters that are activated by high energy.
I do agree with the system needing to be moved, preferably to an exterior wall. I'll look into it.
